export 'package:flutter/material.dart';
export 'package:flutter_addition_hills/components/custom_scaffold.dart';
export 'package:flutter_addition_hills/pages/admin_page.dart';
export 'package:flutter_addition_hills/pages/document_request_page.dart';
// import 'package:flutter_addition_hills/pages/homepage_page.dart';
export 'package:flutter_addition_hills/user_side/log_in/login_page.dart';
export 'package:flutter_addition_hills/pages/signup_page.dart';
//import 'package:flutter_addition_hills/pages/signup_page.dart';
//import 'package:flutter_addition_hills/pages/homepage_page.dart';
//import 'package:flutter_addition_hills/pages/loading_page.dart';
export 'package:flutter/gestures.dart';
export 'package:flutter_addition_hills/user_side/sign_up/components/password_textfield.dart';
export 'package:flutter_addition_hills/user_side/sign_up/components/without_icon_textfield.dart';
export 'package:google_fonts/google_fonts.dart';
export 'package:flutter_addition_hills/utils/extensions.dart';
export 'package:intl_phone_field/intl_phone_field.dart';
export 'package:flutter_addition_hills/components/custom_appbar.dart';
export 'package:flutter_addition_hills/routes/routes.dart';
